fix a syntax bug that was wreaking havoc
... a simple comment caused the first value in the dependencies array to be unintentionally interpreted as undefined!
Uncaught Error: [$injector:modulerr] Failed to instantiate module ShoppinPalApp due to:
Error: [$injector:modulerr] Failed to instantiate module undefined due to:
Error: [ng:areq] Argument 'module' is not a function, got undefined
http://errors.angularjs.org/1.2.28/ng/areq?p0=module&p1=not%20a%20function%2C%20got%20undefined
    at https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:78:12
    at assertArg (https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:1509:11)
    at assertArgFn (https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:1519:3)
    at https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:3891:11
    at forEach (https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:325:18)
    at loadModules (https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:3871:5)
    at https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:3878:40
    at forEach (https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:325:18)
    at loadModules (https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:3871:5)
    at createInjector (https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:3811:11)
http://errors.angularjs.org/1.2.28/$injector/modulerr?p0=undefined&p1=Error…lkit6.localtunnel.me%2Fbower_components%2Fangular%2Fangular.js%3A3811%3A11)
    at https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:78:12
    at https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:3905:15
    at forEach (https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:325:18)
    at loadModules (https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:3871:5)
    at https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:3878:40
    at forEach (https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:325:18)
    at loadModules (https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:3871:5)
    at createInjector (https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:3811:11)
    at doBootstrap (https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:1444:20)
    at bootstrap (https://warepulkit6.localtunnel.me/bower_components/angular/angular.js:1459:12)
http://errors.angularjs.org/1.2.28/$injector/modulerr?p0=ShoppinPalApp&p1=E…lkit6.localtunnel.me%2Fbower_components%2Fangular%2Fangular.js%3A1459%3A12)